### ISSUE TITLE
Is the project still maintained (update 2024)?

### ISSUE THREAD

**Issue by LeoSpyke** [TomasBouda/PoShLog#42]
The title says it clearly. Can we rely on this module for our projects or should we consider it as unmaintained?
In such case, is there any other project that you would suggest as a valid replacement for PoShLog?

Thank you for the clarification.

@gitbute @mamidenn @BradyShober @cdhunt

**Comment by TomasBouda** [comment]
Hi @LeoSpyke
at this moment the project is not actively maintained since I have very little spare time, but I have it on my todo list, were I'm planning to convert it to binary module, add more functions and release v3.0.0. I just don't want to promise something or estimate when it's going to happen. In the meantime I'm able to help with minor issues asked in discussions.
**So in short - it's not maintaned, but not dead** 😏 

As for the alternative for this project, I don't know any similar projects as direct replacement for PoShLog(that was the reason I wrote it back then), but maybe other users might help here.

**Comment by cdhunt** [comment]
The bulk of the functionality comes from Serilog which is well maintained. This wrapper module won't change much unless there is a new version of Serilog with breaking changes which I would be very surprised if that happened.
